version: '3.2'

services:

  php:
    container_name: jamik_php
    build: ./docker/php
    volumes:
      - ./:/app
    depends_on:
      - mysql

  nginx:
    container_name: jamik_nginx
    image: 'nginx:alpine'
    restart: always
    volumes:
      - ./docker/nginx//nginx.template:/etc/nginx/conf.d/nginx.template
      - ./:/app
      - ./.logs/nginx:/var/log/nginx
    ports:
      - 80:80
    env_file: .env
    environment:
      - NGINX_API_HOST=${API_HOST}
      - NGINX_API_PORT=80
      - NGINX_BACKEND_HOST=${BACKEND_HOST}
      - NGINX_BACKEND_PORT=80
      - NGINX_FRONTEND_HOST=${FRONTEND_HOST}
      - NGINX_FRONTEND_PORT=80
      - NGINX_STATIC_HOST=${STATIC_HOST}
      - NGINX_STATIC_PORT=80
    command: sh -c "envsubst '$$NGINX_BACKEND_HOST $$NGINX_BACKEND_PORT $$NGINX_FRONTEND_HOST $$NGINX_FRONTEND_PORT $$NGINX_API_HOST $$NGINX_API_PORT $$NGINX_STATIC_HOST $$NGINX_STATIC_PORT' < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - php

  mysql:
    container_name: jamik_mysql
    image: mariadb:10.4
    volumes:
      - /var/lib/mysql
      - ./docker/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
    ports:
      - 3306:3306
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}

#  postgres:
#    container_name: postgres_billing
#    build: ./docker/postgres
#    restart: always
#    env_file: .env
#    environment:
#      - POSTGRES_USER=${DB_USERNAME}
#      - POSTGRES_PASSWORD=${DB_PASSWORD}
#      - POSTGRES_DB=${DB_NAME}
#      - DB_NAME=${DB_NAME}_testing
#      - DB_USER=${DB_USERNAME}_testing
#      - DB_PASS=${DB_PASSWORD}
#    volumes:
#      - './.database:/var/lib/postgresql/data'
#    ports:
#      - '5432:5432'
